"""Python client for BEAM transfer creation and management."""

from beam_network_sdk._client import (
    BEAM_DEFAULT_MULTIPART_CONTROL_CONCURRENCY,
    BEAM_DEV_URL,
    BEAM_PROD_URL,
    BeamSDK,
    TransferManager,
)
from beam_network_sdk._multipart_limits import (
    MULTIPART_ATTEMPT_SLOT_COUNT,
    MULTIPART_ATTEMPT_SLOTS,
    MULTIPART_MAX_PART_NUMBER,
    MULTIPART_MAX_SOURCE_CHUNKS,
    multipart_part_number,
)
from beam_network_sdk._nats_control import (
    BEAM_ROUTE_TARGET_PAYLOAD_BYTES,
    TransferTerminalSignalWaiter,
)
from beam_network_sdk._nats_control import (
    DEFAULT_MAX_PAYLOAD_BYTES as BEAM_DEFAULT_MAX_PAYLOAD_BYTES,
)
from beam_network_sdk.cancellation import BeamCancellationToken
from beam_network_sdk.exceptions import (
    BeamAPIError,
    BeamAuthError,
    BeamCancelledError,
    BeamError,
    BeamProviderTransferError,
    BeamRouteRecoveryPendingError,
    BeamStorageAccessError,
    BeamTimeoutError,
    BeamTransferError,
    BeamTransferFailedError,
    transfer_failed_error,
)
from beam_network_sdk.models import (
    AttachSignedUrlsResponse,
    AzureProviderDestination,
    AzureProviderSource,
    CallbackConfig,
    ChunkDestinationSigningTarget,
    ChunkSigningPlanItem,
    CompactTransferPlanDescriptor,
    CompactTransferPlanDestination,
    CompactTransferPlanFormulas,
    CompactTransferPlanSource,
    CompletedMultipartUpload,
    DestConfig,
    DestinationObjectInfo,
    DestinationStatusInfo,
    DistributeResponse,
    GCSProviderDestination,
    GCSProviderSource,
    HippiusProviderDestination,
    HippiusProviderSource,
    HuggingFaceProviderDestination,
    HuggingFaceProviderSource,
    HuggingFaceRepoType,
    IntegrityAuditChallenge,
    IntegrityAuditChallengeChunk,
    MultipartGroupManifest,
    MultipartPart,
    PlanningHttpSource,
    PreparedDestination,
    PreparedHttpSource,
    ProviderDestinationConfig,
    ProviderMultipartGroupIdentity,
    ProviderSourceConfig,
    R2ProviderDestination,
    R2ProviderSource,
    S3CompatibleProviderDestination,
    S3CompatibleProviderSource,
    S3ProviderDestination,
    S3ProviderSource,
    SignedChunkRoute,
    SourceConfig,
    SourceStatusInfo,
    TransferCancelResponse,
    TransferCreateRequest,
    TransferCreateResponse,
    TransferPlanResponse,
    TransferPrepareResponse,
    TransferStatusInfo,
    TransferTerminalEvent,
)
from beam_network_sdk.provider_signing import (
    abort_multipart_upload,
    complete_multipart_upload,
    create_multipart_upload,
    expires_at_iso,
    inspect_destination_object,
    is_s3_compatible_provider,
    list_multipart_parts,
    prepare_provider_destination,
    prepare_provider_source,
    prepare_provider_source_for_plan,
    s3_compatible_endpoint,
    s3_compatible_force_path_style,
    s3_compatible_region,
    sign_abort_multipart_upload,
    sign_complete_multipart_upload,
    sign_destination_read_range,
    sign_destination_route,
    sign_destination_url,
    sign_final_object_head,
    sign_list_multipart_upload,
    sign_source_read_range,
)


def _resolve_version() -> str:
    """Report the installed distribution's version.

    The version is declared once, in pyproject.toml. Reading it back from
    package metadata keeps this module from drifting out of step with it, as a
    second hardcoded literal previously did.
    """
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version("beam-network-sdk")
    except PackageNotFoundError:  # running from a source tree, not installed
        return "0.0.0.dev0"


__version__ = _resolve_version()

__all__ = [
    "BeamSDK",
    "TransferManager",
    "BEAM_DEV_URL",
    "BEAM_PROD_URL",
    "BEAM_DEFAULT_MAX_PAYLOAD_BYTES",
    "BEAM_DEFAULT_MULTIPART_CONTROL_CONCURRENCY",
    "BEAM_ROUTE_TARGET_PAYLOAD_BYTES",
    "MULTIPART_ATTEMPT_SLOT_COUNT",
    "MULTIPART_ATTEMPT_SLOTS",
    "MULTIPART_MAX_PART_NUMBER",
    "MULTIPART_MAX_SOURCE_CHUNKS",
    "multipart_part_number",
    "SourceConfig",
    "DestConfig",
    "S3ProviderSource",
    "S3ProviderDestination",
    "R2ProviderSource",
    "R2ProviderDestination",
    "GCSProviderSource",
    "GCSProviderDestination",
    "AzureProviderSource",
    "AzureProviderDestination",
    "HippiusProviderSource",
    "HippiusProviderDestination",
    "S3CompatibleProviderSource",
    "S3CompatibleProviderDestination",
    "HuggingFaceProviderSource",
    "HuggingFaceProviderDestination",
    "HuggingFaceRepoType",
    "MultipartGroupManifest",
    "ProviderMultipartGroupIdentity",
    "ProviderSourceConfig",
    "ProviderDestinationConfig",
    "PlanningHttpSource",
    "PreparedHttpSource",
    "PreparedDestination",
    "MultipartPart",
    "CompletedMultipartUpload",
    "DestinationObjectInfo",
    "ChunkDestinationSigningTarget",
    "ChunkSigningPlanItem",
    "CompactTransferPlanDescriptor",
    "CompactTransferPlanDestination",
    "CompactTransferPlanFormulas",
    "CompactTransferPlanSource",
    "SignedChunkRoute",
    "CallbackConfig",
    "TransferCreateRequest",
    "TransferCreateResponse",
    "TransferPlanResponse",
    "TransferPrepareResponse",
    "TransferCancelResponse",
    "AttachSignedUrlsResponse",
    "DestinationStatusInfo",
    "SourceStatusInfo",
    "IntegrityAuditChallenge",
    "IntegrityAuditChallengeChunk",
    "TransferStatusInfo",
    "TransferTerminalEvent",
    "TransferTerminalSignalWaiter",
    "DistributeResponse",
    "BeamCancellationToken",
    "prepare_provider_source",
    "prepare_provider_source_for_plan",
    "prepare_provider_destination",
    "sign_destination_route",
    "sign_destination_url",
    "list_multipart_parts",
    "complete_multipart_upload",
    "inspect_destination_object",
    "sign_source_read_range",
    "sign_destination_read_range",
    "create_multipart_upload",
    "abort_multipart_upload",
    "sign_complete_multipart_upload",
    "sign_abort_multipart_upload",
    "sign_list_multipart_upload",
    "sign_final_object_head",
    "expires_at_iso",
    "is_s3_compatible_provider",
    "s3_compatible_endpoint",
    "s3_compatible_region",
    "s3_compatible_force_path_style",
    "BeamError",
    "BeamAuthError",
    "BeamAPIError",
    "BeamCancelledError",
    "BeamTransferError",
    "BeamProviderTransferError",
    "BeamRouteRecoveryPendingError",
    "BeamTimeoutError",
    "BeamTransferFailedError",
    "BeamStorageAccessError",
    "transfer_failed_error",
]
